### ISSUE TITLE
Make the documentation in english!

### ISSUE THREAD

**Issue by tlfbrito** [yahoojapan/ConfigCacheBundle#15]
Please change the documentation and readme files to english!

**Comment by msmsny** [comment]
I'll do it.

**Comment by felipsmartins** [comment]
+1
Since [Symfony News](https://twitter.com/symfony_en/status/702781427105062912) has annunced on Tweeter about Yahoo Japan using Symfony it'll have a lot of hits.

**Comment by msmsny** [comment]
This has been done.
